# Generated by Django 4.1.2 on 2022-10-27 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='profile',
            name='account',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
            preserve_default=False,
        ),
    ]
