# Generated by Django 3.0.7 on 2020-09-26 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.Bookmark')),
            ],
        ),
    ]
