# Generated by Django 3.0.7 on 2020-09-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_bookmark_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
