# Generated by Django 4.1.2 on 2022-10-27 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_change_active_to_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
